name: frontend
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.8
  device_preview: ^1.1.0
  flutter_timer_countdown: ^1.0.5
  flutter_svg: ^2.0.5
  spider: ^4.2.2
  jwt_decoder: ^2.0.1
  http: ^1.4.0
  google_fonts: ^6.2.1
  provider: ^6.1.5
  fl_chart: ^1.0.0
  syncfusion_flutter_charts: ^30.2.7
  file_picker: ^8.0.0
  lottie: ^2.7.0

  #flutter_icons:
  #  path: ./flutter-icons

  json_annotation: ^4.8.1
  json_serializable: 6.8.0
  build_runner: ^2.4.6
  intl: ^0.20.2
  table_calendar: ^3.0.0
  flutter_screenutil: ^5.0.0+2
  smooth_page_indicator: ^1.2.1
  colorize_text_avatar: ^1.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  very_good_analysis: ^9.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/vectors/
    - assets/img1.jpeg
    - assets/img2.jpeg
    - assets/logo.png
    - assets/top_shape1.jpg
    - assets/Copilot_20250904_052648.png
    - assets/image.png
    - assets/istockphoto.jpg
    - assets/lottie/loading.json
    - assets/lottie/Book Animation.json
    - assets/lottie/education new color scheme.json
    - assets/lottie/Search for value.json
    - assets/lottie/abstract.json
